1.Given a 1D array, negate all elements which are between 3 and 8, in place (not created a new array).

In [1]:
import numpy as np 
a = np.arange(0,11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [2]:
a[(3 <= a) & (a <= 8)] *= -1
a

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

2.Create random vector of size 10 and replace the maximum value by 0

In [3]:
import numpy as np 
a = np.random.randint(0,10,10)
a

array([3, 0, 4, 5, 8, 9, 2, 5, 1, 5])

In [4]:
a[np.argmax(a)] = 0
a

array([3, 0, 4, 5, 8, 0, 2, 5, 1, 5])

3.How to find common values between two arrays?

In [5]:
import numpy as np 
a = np.random.randint(0,100,50)
a

array([ 3,  3, 68, 95, 47, 50, 75, 26,  5, 45, 46, 51, 41, 67, 41, 17, 42,
       69, 15, 55, 72,  0, 26,  4, 38, 19, 14, 77, 49, 51, 19, 56, 62, 58,
       23, 24, 70, 38, 20, 98, 98, 57, 43,  3, 34, 12, 29, 71, 71,  2])

In [6]:
b = np.random.randint(0,100,50)
b

array([97, 17,  3,  4, 30, 73, 33, 65, 62,  9, 97, 76, 32, 66, 50, 88, 97,
       24, 59, 90, 41, 73, 45, 72,  7, 46, 18, 51, 83, 45, 85,  0, 21, 43,
       88, 85, 99, 56, 27, 47, 37, 71, 97, 56, 63,  9,  0, 31, 66, 85])

In [7]:
c=(np.intersect1d(a,b))
c

array([ 0,  3,  4, 17, 24, 41, 43, 45, 46, 47, 50, 51, 56, 62, 71, 72])

4.Reverse a vector (first element becomes last)

In [8]:
import numpy as np 
a = np.arange(1,20)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [9]:
a[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1])

5.Create a 3x3 matrix with values ranging from 0 to 8

In [10]:
import numpy as np 
a = np.random.randint(0,9,(3,3))
a

array([[1, 8, 7],
       [3, 1, 3],
       [5, 1, 2]])

6.Find indices of non-zero elements from the array [1,2,0,0,4,0]

In [11]:
import numpy as np 
a = np.array([1,2,0,0,4,0])
a

array([1, 2, 0, 0, 4, 0])

In [12]:
np.where(a != 0)

(array([0, 1, 4], dtype=int64),)

7.Create a 3x3x3 array with random values

In [13]:
import numpy as np 
a = np.random.randint(-1000,1000,(3,3,3))
a


array([[[-492, -657, -585],
        [ 857,   92,  791],
        [-304,  646, -723]],

       [[ 278, -768, -266],
        [ -58,  857,  393],
        [ 978,  296,  986]],

       [[-226,  982, -497],
        [  22, -410,  948],
        [ 984,  274, -934]]])

8.Create a random vector of size 30 and find the mean value

In [14]:
import numpy as np 
a = np.random.random(30)
a

array([0.94118994, 0.86159017, 0.25899095, 0.14629643, 0.80024961,
       0.60580908, 0.02044291, 0.4122771 , 0.40759255, 0.1303528 ,
       0.43464317, 0.76045587, 0.66430081, 0.98947451, 0.99739523,
       0.19222868, 0.36707259, 0.52307265, 0.08340633, 0.11439746,
       0.06538945, 0.42136494, 0.71813589, 0.12478066, 0.31581179,
       0.82509922, 0.90597305, 0.95448944, 0.97302956, 0.55386778])

In [15]:
np.mean(a)

0.5189726875709152

9.Create a 2d array with 1 on the border and 0 inside

In [16]:
import numpy as np
a = np.ones((10,10))
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [17]:
a[1:-1,1:-1]=0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])