3.How to find common values between two arrays?

In [32]:
import numpy as np 
a = np.random.randint(0,100,50)
a

array([42, 71, 37, 38,  3,  0, 37,  9,  2, 30, 55,  9, 92, 50,  6, 25, 48,
       78, 93, 21, 37, 51, 37, 97, 70, 97, 55, 85, 86, 78, 60, 65, 70, 60,
        6, 34, 70, 11, 79,  1, 23, 82, 88, 88, 19, 75,  6, 42, 33, 56])

In [33]:
b = np.random.randint(0,100,50)
b

array([11,  2, 40, 44, 54, 53, 68,  6, 37, 38, 60, 62, 82, 89, 78, 45, 35,
       38, 30, 85, 12, 91, 31, 90, 50, 88, 53, 13, 30, 28, 94, 87, 30, 35,
       83, 93,  4, 33, 50, 91, 22, 16, 10, 91, 48,  7, 99, 87, 21, 40])

In [34]:
c=(np.intersect1d(a,b))
c

array([ 2,  6, 11, 21, 30, 33, 37, 38, 48, 50, 60, 78, 82, 85, 88, 93])